version: '3.8'
services:
  app:
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
    command: npm run start:dev
  db:
    ports:
      - "5432:5432"
