version: '3.8'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: dockerfile
    environment:
      db_host: db
      db_port: ${db_port}
      db_user: ${db_user}
      db_password: ${db_password}
      db_database: ${db_database}
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${db_user}
      POSTGRES_PASSWORD: ${db_password}
      POSTGRES_DB: ${db_database}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
